<a href="https://colab.research.google.com/github/sushanttwayana/Learning-Machine-Learning/blob/main/ML_Day_1(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy


In [ ]:
import numpy as np

# Create a row vector
row_vector = np.array([10, 20, 30])
print(row_vector)

# Create a column vector
col_vector = np.array([[10],[20], [30]])
print(col_vector)

print("row_vector[1]:", row_vector[1])

print("row_vector[:]", row_vector[:])

[10 20 30]
[[10]
 [20]
 [30]]
row_vector[1]: 20
row_vector[:] [10 20 30]


In [ ]:
# Create a matrix

matrix = np.array([[10, 20, 30], [40,50, 60], [70, 80, 90]])
print(matrix)

print("matrix[2][2]:", matrix[2][2])

print("matrix[:2, :]:", matrix[:2, :])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
matrix[2][2]: 90
matrix[:2, :]: [[10 20 30]
 [40 50 60]]


In [ ]:
matrix = np.array([[10, 20, 30], [40,50, 60], [70, 80, 90]])

# View the number of rows and columns of the matrix
print("Rows and Columns:", matrix.shape)

# View the number of elements (rows* columns)
print("Total Elements:", matrix.size)

# View the dimension of the matrix
print("Dimension:", matrix.ndim)

Rows and Columns: (3, 3)
Total Elements: 9
Dimension: 2


In [ ]:
# Min and Max in matrix

matrix = np.array([[10, 20, 30], [40,50, 60], [70, 80, 90]])

print("Max element :", np.max(matrix))

print("Min element :", np.min(matrix))

# To find the max element in each column
print(np.max(matrix, axis = 0))

# To find the max element in each row
print(np.max(matrix, axis = 1))

# calculate the average
print("Average of elements:", np.mean(matrix))


Max element : 90
Min element : 10
[70 80 90]
[30 60 90]
Average of elements: 50.0


In [ ]:
# Reshaping

matrix = np.array([[10, 20, 30], [40,50, 60], [70, 80, 90]])
print(matrix)

# Reshape
print(matrix.reshape(1,9))

# 1 indicates row and -1 indicates as many as columns needed
print(matrix.reshape(1, -1))

# If we provide only 1 value in reshape it would only return 1d array of that length
print(matrix.reshape(9))

# we can also use flatten to convert the matrix into 1d array
print(matrix.flatten())

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30 40 50 60 70 80 90]]
[[10 20 30 40 50 60 70 80 90]]
[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


In [ ]:
# Transpose of the matrix

print("Matrix:\n",matrix)
print("Transpose:\n", matrix.T)

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Transpose:
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [ ]:
# Print the principal diagonal

print("Diagonal elem:", np.diagonal(matrix))
print("Diagonal elem:", matrix.diagonal())

Diagonal elem: [10 50 90]
Diagonal elem: [10 50 90]


In [ ]:
# Dot Product

vector_1 = np.array([10, 20, 30])
vector_2 = np.array([40, 50, 60])

# Calculate the dot product

print(np.dot(vector_1, vector_2))

3200


In [ ]:
# Adding , Subrtracction and Multiplication of two matrices

matrix1 = np.array([[10, 20, 30], [40,50, 60], [70, 80, 90]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix1)
print(matrix2)

# additon
print(np.add(matrix1, matrix2))

# subtraction
print(np.subtract(matrix1, matrix2))

# multiplication ( Element wise multipication)
print(matrix1 * matrix2)

# for dot multiplication ie (row column wise)
print(np.matmul(matrix1, matrix2))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [ ]:
# Create matrix element all of 0's and 1's

zeros = np.zeros([4, 4])
print(zeros)

ones = np.ones([3, 3])
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# generate random numbers

# Generate 3 random numbers in bw 1 and 10
print(np.random.randint(0, 11, 3))

# Draw 6 numbers from a normal distribution with mean 1.0 and std 2.0

print(np.random.normal(1.0, 2.0, 6))

[6 6 8]
[3.0549914  2.64766884 1.30899828 2.43544766 0.30709413 2.00790431]
